# Travis build file for checking for errors.

sudo: false

before_install:
- git clone https://github.com/eurocris/CERIF-TG-Tools.git ../CERIF-TG-Tools
- git clone https://github.com/jdvorak001/openaire-cris-validator.git ../openaire-cris-validator

language: java

jdk:
    - openjdk8

install: true

script:
    - travis_wait ./tools/compile.sh
