# Travis build file for checking for errors.

sudo: false

language: java

jdk:
    - openjdk8

install: true

script:
    # this runs two Maven goals: transform and validate
    - travis_wait mvn test -B